export const copy = {
  app: {
    name: 'MoodSignals',
    subtitle: 'Private on this device.',
    privacySheetTitle: 'Your privacy',
    privacySheetBody: [
      'MoodSignals stores your data on this device.',
      'Use Export/Import to move data between devices.',
      'Sign-in sync is planned for later.',
    ],
    helpAction: 'Help',
  },
  nav: {
    insights: 'Insights',
    today: 'Today',
    timeline: 'Timeline',
    data: 'Import',
    settings: 'Settings',
  },
  common: {
    info: 'Info',
    close: 'Close',
    details: 'Details',
    evidence: 'Evidence',
    deleteAll: 'Delete all',
    exportData: 'Export data',
    importData: 'Import data',
    syncOptional: 'Sync is optional. Local-only by default.',
    confidenceLevel: {
      High: 'High: enough data',
      Med: 'Medium: building up',
      Low: 'Low: need more logs',
    },
  },
  insights: {
    title: 'Insights',
    startTitle: 'Start here',
    startInfoTitle: 'Quick start',
    startInfoBody: [
      'Try demo data for an instant preview.',
      'Log today to build your own trend.',
      'Import transactions if you have CSV.',
    ],
    demoAction: 'Try demo data',
    logAction: 'Log today',
    importAction: 'Import transactions',
    readinessTitle: 'Data readiness',
    readinessInfoTitle: 'How this works',
    readinessInfoBody: [
      'Moods this week: mood check-ins in 7 days.',
      'Spend records 30d: spend logs plus transactions.',
      'Mood-tagged purchases: tagged transactions only.',
    ],
    moodsMetric: 'Moods this week',
    spendMetric: 'Spend records 30d',
    taggedMetric: 'Mood-tagged purchases',
    feedTitle: 'Signal cards',
    feedSubtitle: 'Eight quick signals.',
    emptyCards: 'Add a log to unlock cards.',
    demoLoaded: 'Demo data loaded.',
    demoFailed: 'Could not load demo data.',
  },
  today: {
    title: 'Today',
    moodUnlock: 'Mood log added.',
    spendUnlock: 'Spend log added.',
    saved: 'Saved.',
    statusTitle: 'Saved',
    infoTitle: 'Why today',
    infoBody: [
      'Two quick logs are enough.',
      'More tagged data makes insights clearer.',
    ],
  },
  timeline: {
    title: 'Timeline',
    filterAction: 'Filters',
    filterTitle: 'Timeline filters',
    resetFilters: 'Clear',
    tagAction: 'Tag purchases',
    emptyTitle: 'No events yet',
    emptySubtitle: 'Log today or import data.',
    listInfoTitle: 'What appears here',
    listInfoBody: [
      'Mood check-ins',
      'Spend moments',
      'Imported transactions',
    ],
    typeAll: 'All types',
    typeMood: 'Mood',
    typeSpend: 'Spend',
    typeTransaction: 'Transaction',
  },
  data: {
    title: 'Import',
    moveTitle: 'Move devices',
    importHistory: 'Import history',
    importInfoTitle: 'How to find CSV',
    importInfoBody: [
      'Open your bank or card activity page.',
      'Choose Export or Download as CSV.',
      'If you only have Excel, save as CSV.',
      'PDF statements are not supported.',
    ],
    importStatusReady: 'Ready to import.',
    importStatusMissing: 'Map Date and Amount to continue.',
    importStatusError: 'This file does not look like CSV.',
    importDone: 'Imported on this device.',
    transferDone: 'JSON exported.',
    transferImported: 'JSON imported.',
    transferFailed: 'JSON import failed.',
    loadDemo: 'Load demo data',
    resetDemo: 'Reset demo data',
    csvTemplate: 'Template CSV',
    csvExport: 'Export CSV',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Privacy and sync.',
    privacyTitle: 'Privacy controls',
    privacySubtitle: 'Manage local data.',
    accountTitle: 'Account & Sync (Coming Soon)',
    accountSubtitle: 'Optional in V2.',
    localMode: 'Local-only mode (default)',
    accountLineOne: 'MoodSignals runs on your device for privacy.',
    accountLineTwo: 'To move data now: Export/Import.',
    accountLineThree: 'Sign-in sync will be added later.',
    tutorialTitle: 'Tutorial',
    openHelp: 'Help',
    resetTutorial: 'Reset tutorial',
    resetTutorialDone: 'Tutorial reset.',
    countTitle: 'Stored items',
    countMoods: 'Mood logs',
    countSpends: 'Spend moments',
    countTransactions: 'Transactions',
    countImports: 'Imports',
    syncStatusOn: 'Sync UI enabled.',
    syncStatusOff: 'Enable with VITE_ENABLE_SYNC=true.',
    providerGoogle: 'Continue with Google',
    providerApple: 'Continue with Apple',
    providerKakao: 'Continue with Kakao',
    signInLabel: 'Sign in to sync (coming soon)',
    deleteWarning: 'This deletes local data.',
  },
  onboarding: {
    slides: [
      {
        title: 'What this is',
        sentence: 'See how moods shape spending—without judgment.',
        bullets: ['Your pace', 'No shaming', 'Small steps count'],
        icon: '✨',
      },
      {
        title: 'Two quick logs',
        sentence: "Log a mood. Log a spend moment. That's enough.",
        bullets: ['Done in minutes', 'Any day counts'],
        icon: '📝',
      },
      {
        title: 'Import optional',
        sentence: 'Import bank CSV if you have it. Not required.',
        bullets: ['Bring history faster', 'Skip if not ready'],
        icon: '📥',
      },
      {
        title: 'Tag moods on purchases',
        sentence: 'Attach a mood to purchases you remember.',
        bullets: ['Tag now', 'Edit later'],
        icon: '🏷️',
      },
      {
        title: 'Insights become clearer',
        sentence: 'More tagged data → stronger insights.',
        bullets: ['Patterns sharpen', 'Next steps improve'],
        icon: '📈',
      },
      {
        title: 'Privacy',
        sentence: 'Your data stays on this device.',
        bullets: ['No account needed', 'You stay in control'],
        icon: '🔒',
      },
      {
        title: 'No login yet',
        sentence: 'Login is coming. For now, use Export/Import to move data.',
        bullets: ['Local-first today', 'Sync in V2'],
        icon: '🔑',
      },
    ],
    back: 'Back',
    next: 'Next',
    done: 'Start using MoodSignals',
    skip: 'Skip',
    suppress30Days: "Don't show for 30 days",
  },
} as const

export const copyBudget = {
  maxTitleWords: 4,
  maxDescriptionWords: 12,
} as const
